---
title: "Extreme Meteorological Year 8760s"
author: "Cal-Adapt Analytics Engine Team"
date: "2024-06-26"
date-modified: "2026-06-26"
format:
  html: default
  pdf: default
resources:
  - figures/html/
---

## Overview 
XMY climate profiles provide the same weather variables provided in a TMY profile, but intentionally preserves or characterizes extreme weather event representation within a one-year climate profile. There is currently no one recommended or accepted methodology for calculating an XMY. However, the general intent of an XMY is to select more extreme months (e.g., [Crawley and Lawrie 2015](https://publications.ibpsa.org/proceedings/bs/2015/papers/bs2015_2707.pdf); [Crawley and Lawrie 2019](https://climate.onebuilding.org/papers/2019_09%20ShouldWeBeUsingTypicalWeatherData-BS2019_210594.pdf); [Bass and New 2020](https://www.osti.gov/servlets/purl/1735419); [Zeng et al. 2025](https://www.sciencedirect.com/science/article/abs/pii/S1364032124009390?via%3Dihub)) instead of the median conditions represented in a TMY, and to use a large set of climate model simulations to do so. However, no one XMY can meet the planning objectives for all use cases.

Rather than requiring users to determine which approach may be appropriate for their application, Cal-Adapt provides standardized, purpose-built profiles tailored to common energy-sector use cases for different extreme types:
- **Shock Event XMY**: An extreme climate profile that is representative of *short-term event-wise pulses* that increase peak demand, such as a 4-day heatwave or a 5-day coldsnap. The Shock XMY is built upon an extreme cumulative distribution furthest from the median weather conditions for a location over a climatological period. 
- **Persistence XMY**: An extreme climate profile that is representative of *extreme annual metrics*, such as an extreme hot year or an extreme cold year, that can be applied for highly tailorable system stress tests. The Persistence XMY is built upon a given statistical extreme percentile of weather conditions for a location over a climatological period. 

*fig placeholder degree days*

## Applications

## Methodology -- Shock XMY
The Shock Event XMY represents localized weather conditions that strain peak demand by emphasizing the range of variability within a distribution. This method identifies the weather year distribution that differs the greatest from long-term climatology. 
*figure placeholder?*

### Step 1 – Select Location and Planning Horizon. 
Cal-Adapt Shock XMYs are for point-based locations, meaning that a user will first select a specific location of interest, such as a power plant or an airport weather station. The user will also select a climatological period of time, such as a global warming level planning horizon centered around 30 years of data, or a time-based 30-year period. Cal-Adapt recommends a GWL-based approach to reduce multi-model uncertainty when using global climate models. 

### Step 2 – Select Shock Extreme Type.
Next, the type of extreme is selected: a hot extreme, representative of extreme heat conditions and heatwaves, or a cold extreme, representative of extreme cold conditions such as a cold snap. Based on industry partner interviews, **extreme weather conditions are most commonly characterized by the temperature profile**, reflecting the critical role temperature plays in defining system stress.

### Step 3 – Retrieve and Process Hourly Air Temperature.
Hourly air temperature is retrieved for the location and climatology selections as the determining environmental factor for extreme characterization. This differs from the TMY approach which includes 10 environmental metrics, including solar radiation and wind speed ([Wilcox and Marion 2008](https://docs.nrel.gov/docs/fy08osti/43156.pdf), [ISO 15927-4](https://www.iso.org/standard/41371.html)). Air temperature is then resampled to the corresponding extreme type. For a cold extreme profile, the data is resampled to daily minimum temperature. For hot extremes, the data is resampled to daily maximum temperature. Cal-Adapt uses a priori bias-adjusted dynamically downscaled WRF model outputs as the data foundation for TMY and XMY profiles.

### Step 4 – Calculate the Maximized Error between Climatology and Extreme Months.
For each month, two sets of cumulative distribution functions (CDF) are calculated: one for the long-term median climatology across all candidate years, and one for each year within the climatology (i.e., a candidate year). The candidate year is compared against climatology to quantitatively select the month that is furthest from the long-term median conditions, maximizing the error. For cold extremes, this translates to the lowest-value month or maximized negative error relative to climatology. For hot extremes, the highest-value month or maximized positive error relative to climatology is selected (Figure 2). This process is repeated for all months, per simulation. Doing so ensures that model data is kept intact within a single physically-consistent climate profile, rather than pooling across models which introduces multi-model uncertainty. Following TMY methodological best practice, years of abnormal volcanic activity are excluded from consideration due to the impact of aerosols on air temperatures. 
*figure placeholder*

### Step 5 – Compile Extreme Months and Generate XMY Profile.
Once the most extreme months are selected, the standard meteorological information included in a TMY profile are retrieved for contemporaneous months (Figure 3). XMY profiles therefore include: air temperature, dewpoint temperature, relative humidity, global irradiance, direct irradiance, diffuse irradiance, downwelling radiation, wind speed and direction, and surface air pressure for each of the designated months as determined by the extreme air temperature profile. In other words, if February 2005 is the most extreme month for a cold Shock XMY, all other variables are explicitly extracted for February 2005 to maintain a physically consistent profile. Smoothing at the monthly interface between months is performed via second-degree polynomial curve fit to prevent discontinuities at the month interface ([Wilcox and Marion 2008](https://docs.nrel.gov/docs/fy08osti/43156.pdf)). 

## Methodology -- Persistence XMY
The Persistence XMY represents localized weather conditions that stress an energy system by selecting hours associated with specific percentile-based extremes within the climatological distribution, prioritizing sustained statistical deviation from typical conditions. This method allows precise tuning for exact conditions in order to stress test systems, such as “turning a dial” on the intensity of the desired extreme. 
*figure placeholder?*

### Step 1 – Select Location and Planning Horizon. 
Cal-Adapt Persistence XMYs are for point-based locations, meaning that a user will first select a specific location of interest, such as a power plant or an airport weather station. The user will also select a climatological period of time, such as a global warming level centered around 30 years of data, or a time-based 30-year period. Cal-Adapt recommends a GWL-based approach to reduce multi-model uncertainty when using global climate models. 

### Step 2 – Select Extreme Percentile. 
The Persistence XMY is calculated by applying the Cal-Adapt: Standard Year methodology in which the desired percentile is calculated from the long-term climatological distribution and the closest value from the distribution of simulation values at a given hour is returned for each hour of the year. The lower percentiles (below median conditions at the 50th percentile) represent cold extremes. Upper percentiles (above median conditions at the 50th percentile) provide hot extremes. 

### Step 3 – Retrieve Hourly Air Temperature.
Hourly air temperature is retrieved for the location and climatology selections as the determining environmental factor for extreme characterization. This differs from the TMY approach which includes 10 environmental metrics, including solar radiation and wind speed ([Wilcox and Marion 2008](https://docs.nrel.gov/docs/fy08osti/43156.pdf), [Crawley and Lawrie 2019](https://doi.org/10.26868/25222708.2019.210594)). Based on industry user interviews, **extreme conditions are most commonly characterized by the temperature profile**, reflecting the critical role temperature plays in defining system stress. Cal-Adapt uses a priori bias-adjusted dynamically downscaled WRF model outputs as the data foundation for TMY and XMY profiles.

### Step 4 – Calculate the Hourly Distribution.
Using hourly air temperature, the closest value to the desired percentile is returned for each hour of the year, per model. This process is repeated for all bias-adjusted model simulations. Doing so ensures that model data is kept intact within a single climate profile, rather than pooling across models which introduces multi-model uncertainty. Following TMY methodological best practice, years of abnormal volcanic activity are excluded from consideration due to the impact of aerosols on air temperatures.  

### Step 5 – Compile Extreme Hours and Generate XMY Profile.
Once the most extreme conditions are selected, the Persistence XMY is compiled into an hourly timeseries where each hour represents a specific percentile for that hour of the year. The standard meteorological information included in a TMY profile are retrieved for contemporaneous conditions. XMY profiles therefore include: air temperature, dewpoint temperature, relative humidity, global irradiance, direct irradiance, diffuse irradiance, downwelling radiation, wind speed and direction, and surface air pressure as determined by the extreme air temperature profile.
*figure placeholder*

## References
- Wilcox and Marion (2008) Users Manual for TMY3 Data Sets. National Renewable Energy Laboratory Technical Report NREL/TP-581-43156 
- NSRDB: https://nsrdb.nlr.gov/data-sets/tmy 
- Laxo (2023) Climate Forward? How Climate Projections Are(n’t) Used to Inform Design. https://hga.com/climate-forward/ 
- Peltier et al. (2024) A climate-aware built environment: Integrating future weather data into building design today. https://www.aceee.org/sites/default/files/proceedings/ssb24/assets/attachments/20240722160818203_c563a22d-adf2-42fa-9e31-789b98700ad6.pdf
- NYSERDA (2020) Assessment of Future Typical Meteorological Year Data Files. https://www.resourcerefocus.com/ftmy-2020 
- Li et al. (2023) Improvement of methods of obtaining urban TMY and application for building energy consumption simulation. https://doi.org/10.1016/j.enbuild.2023.113300 
- Zeng et al. (2025) A review of future weather data for assessing climate change impacts on buildings and energy systems. https://doi.org/10.1016/j.rser.2024.115213 
- Crawley (1998) Which weather data should you use for energy simulations of commercial buildings? Build Eng 104(2): 498-515. 
- Levermore and Parkinson (2006) Analyses and algorithms for new test reference years and design summer years for the UK. https://doi.org/10.1177/0143624406071037 
- Moazami et al. (2019) Impacts of future weather data typology on building energy performance – investigating long-term patterns of climate change and extreme weather conditions. https://doi.org/10.1016/j.apenergy.2019.01.085 
- Nik (2016) Making energy simulation easier for future climate – synthesizing typical and extreme weather data sets out of regional climate models (RCMs). https://doi.org/10.1177/0143624411418132 
- ASHRAE (2024) Energy Simulation Aided Design for Buildings Except Low-Rise Residential Buildings.  https://www.ashrae.org/file%20library/technical%20resources/standards%20and%20guidelines/standards%20addenda/209_2018_l_20240830.pdf 
- Crawley and Lawrie (2015). Rethinking the TMY: Is the "Typical" Meteorological Year Best for Building Performance Simulation? https://publications.ibpsa.org/proceedings/bs/2015/papers/bs2015_2707.pdf 
- Crawley and Lawrie (2019) Should We Be Using Just “Typical” Weather Data in Building Performance Simulation? https://doi.org/10.26868/25222708.2019.210594 
- Bass and New (2000) Future Meteorological Year weather data from IPCC Scenarios. https://www.osti.gov/servlets/purl/1735419 
- ISO 15927-4 (2005) https://www.iso.org/standard/41371.html 
- Tarkhan et al. (2025) Generation of representative meteorological years through anomaly-based detection of extreme events. https://doi.org/10.1080/19401493.2025.2499687 
- Doutreloup et al. (2022) Historical and future weather data for dynamic building simulations in Belgium using the regional climate model MAR: typical and extreme meteorological year and heatwaves. https://doi.org/10.5194/essd-14-3039-2022 
