project:
  type: website
  pre-render:
    - glossary/generate-glossary.py
    - general-resources/reference-library/generate-reference-library.py
  resources:
    - assets/pdfs/**
    - assets/cards/**

website:
  title: "Cal-Adapt: Analytics Engine"
  site-url: https://analytics.cal-adapt.org
  favicon: assets/favicon.ico
  search: true
  page-navigation: true
  bread-crumbs: true
  open-graph: true
  navbar:
    pinned: true
    logo: assets/bear.png
    logo-alt: "Cal-Adapt Analytics Engine"
    left:
      - text: General Resources
        menu:
          - text: Getting Started
            href: general-resources/getting-started.qmd
          - href: glossary/index.qmd
          - href: general-resources/reference-library.qmd
          - text: Media
            href: general-resources/media/index.qmd
      - text: Scientific Guidance
        menu:
          - href: scientific-guidance/general-climate-guidance/index.qmd
            text: General Climate Guidance
          - href: scientific-guidance/climate_profiles/index.qmd
            text: Climate Profiles
          - href: scientific-guidance/uncertainty/index.qmd
            text: Uncertainty
          - href: scientific-guidance/heat-metrics.qmd
            text: Heat Metrics
          - href: scientific-guidance/census-tracts.qmd
            text: Census Tracts
          - href: scientific-guidance/global-warming-levels.qmd
          - href: scientific-guidance/extreme-value-analysis.qmd
      - text: Data & Tools
        menu:
          - href: data-tools/data-catalog.qmd
          - href: data-tools/data-explorer.qmd
          - href: data-tools/access-methods.qmd
          - text: Data Documentation
            href: data-tools/data-documentation/index.qmd
          - href: data-tools/analytics-engine-hub.qmd
          - href: data-tools/python-tools.qmd
      - href: blog/index.qmd
      - text: About
        menu:
          - href: about/our-project.qmd
          - href: about/co-production.qmd
          - href: about/our-users.qmd
          - href: about/our-team.qmd
  page-footer:
    left: |
      ![](/assets/bear.png){width="24px"} &nbsp;&copy; 2026 Cal-Adapt Analytics Engine
    right:
      - text: "Contact Us"
        href: "mailto:analytics@cal-adapt.org"
      - icon: github
        href: "https://github.com/cal-adapt"
        aria-label: GitHub
  sidebar:
    - id: general-resources
      title: "General Resources"
      style: docked
      collapse-level: 1
      contents:
        - general-resources/getting-started.qmd
        - glossary/index.qmd
        - general-resources/reference-library.qmd
        - text: "Media"
          href: general-resources/media/index.qmd
          contents:
            - general-resources/media/video-tutorials.qmd
            - general-resources/media/webinars.qmd
            - general-resources/media/presentations.qmd
    - id: scientific-guidance
      title: "Scientific Guidance"
      style: docked
      collapse-level: 1
      contents:
        - text: "General Climate Guidance"
          href: scientific-guidance/general-climate-guidance/index.qmd
          contents:
            - scientific-guidance/general-climate-guidance/about-climate-projections.qmd
            - scientific-guidance/general-climate-guidance/using-climate-projections.qmd
            - scientific-guidance/general-climate-guidance/guiding-principles.qmd
        - text: "Climate Profiles"
          href: scientific-guidance/climate_profiles/index.qmd
          contents:
            - scientific-guidance/climate_profiles/climate-profiles-data.qmd
            - scientific-guidance/climate_profiles/standard-year.qmd
            - scientific-guidance/climate_profiles/typical-met-year.qmd
            - scientific-guidance/climate_profiles/extreme-met-year.qmd
        - text: "Uncertainty"
          href: scientific-guidance/uncertainty/index.qmd
          contents:
            - scientific-guidance/uncertainty/model_uncertainty.qmd
            - scientific-guidance/uncertainty/scenario_uncertainty.qmd
            - scientific-guidance/uncertainty/internal_variability.qmd
        - text: Heat Metrics
          href: scientific-guidance/heat-metrics.qmd
        - text: Census Tracts
          href: scientific-guidance/census-tracts.qmd
        - scientific-guidance/global-warming-levels.qmd
        - scientific-guidance/extreme-value-analysis.qmd
    - id: data-tools
      title: "Data & Tools"
      style: docked
      collapse-level: 1
      contents:
        - data-tools/data-catalog.qmd
        - data-tools/data-explorer.qmd
        - data-tools/access-methods.qmd
        - text: "Data Documentation"
          href: data-tools/data-documentation/index.qmd
          contents:
            - data-tools/data-documentation/climate-model-sims.qmd
            - data-tools/data-documentation/data-structure-and-format.qmd
            - data-tools/data-documentation/metadata-standards.qmd
        - data-tools/analytics-engine-hub.qmd
        - data-tools/python-tools.qmd
    - id: about
      title: "About"
      style: docked
      collapse-level: 1
      contents:
        - about/our-project.qmd
        - about/co-production.qmd
        - about/our-users.qmd
        - about/our-team.qmd

bibliography: references.bib
csl: citation-style.csl
reference-section-title: "References"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    format-links: [pdf]
    citation: true
    appendix-cite-as: display
    include-after-body: glossary/_glossary-tooltip-inline.html
  pdf:
    toc: false
    citation: true
    mainfont: Arial
    fontsize: 11pt
    geometry:
      - margin=1in
      - headsep=35pt
    template-partials:
      - templates/title.tex
    filters:
      - filters/pdf-citation.lua
    include-in-header:
      text: |
        \usepackage{fancyhdr}
        \usepackage{graphicx}
        \usepackage{xcolor}
        \definecolor{caladaptorange}{HTML}{F79226}
        \definecolor{caladaptorangelight}{HTML}{FBECDA}
        \usepackage[framemethod=tikz]{mdframed}
        \newmdenv[
          hidealllines=true,
          innerleftmargin=0pt, innerrightmargin=0pt,
          innertopmargin=6pt, innerbottommargin=6pt
        ]{citebox}
        \newmdenv[
          backgroundcolor=caladaptorangelight,
          linecolor=caladaptorange,
          linewidth=0.5pt,
          roundcorner=2pt,
          innerleftmargin=12pt, innerrightmargin=12pt,
          innertopmargin=10pt, innerbottommargin=10pt
        ]{titlebox}
        \graphicspath{{./assets/}{../assets/}{../../assets/}{../../../assets/}}
        \pagestyle{fancy}
        \fancyhf{}
        \fancyfoot[R]{\includegraphics[height=0.8cm]{bear.png}}
        \fancyfoot[C]{\thepage}
        \renewcommand{\headrulewidth}{0pt}
        \renewcommand{\footrulewidth}{0pt}
        \fancypagestyle{plain}{
          \fancyhf{}
          \fancyfoot[L]{\parbox[b]{0.7\linewidth}{\textcolor{caladaptorange}{\textbf{Cal-Adapt}\\Supporting California’s Energy Resilience, Reliability, and Planning}}}
          \fancyfoot[R]{\includegraphics[height=0.8cm]{bear.png}}
          \renewcommand{\headrulewidth}{0pt}
          \renewcommand{\footrulewidth}{0pt}
        }
