---
title: "Guiding Principles on the Use of Climate Data"
author:
  - name: "Kripa Jagannathan"
  - name: "Nancy Freitas"
  - name: "Victoria Ford"
  - name: "Will Krantz"
  - name: "Justine Bui"
  - name: "Owen Doherty"
  - name: "Andrew Jones"
date: "2026-07-15"
date-modified: &date-modified "2026-07-16"
citation:
  publisher: "Cal-Adapt"
  issued: *date-modified
format:
  html: default
  pdf: default
---

## Preamble

The purpose of this page is to provide users of climate data with broad principles and a process that can be followed when working with climate data for different applications. This process goes through the various steps in climate data analyses – from identifying data needs and choosing the right products, to analysing data and reporting on climate-related results. The principles were developed through 2.5 years of iterative deliberations among different scientists of the Cal-Adapt Analytics Engine Project, with regular feedback from key climate data users (including energy utilities) at various steps of the process. The principles try to balance scientific rigor and the practical constraints of data use to afford users different options to work with climate data. These principles can be useful for anyone who is currently integrating or looking to integrate climate data into different applications or decision-contexts.

The principles are presented sequentially and in a step-by-step manner, however a user may follow a different order based on their context. There are also many offramps for this process, and some users may not need to go through all the steps based on their specific contextual needs. This process can be highly iterative and may require certain assumptions and decisions (e.g. metrics, scales, or types of analyses) to be re-visited several times. Although the document presents broad principles that can apply to many different contexts and uses, specific applications will likely require more complex and nuanced examinations within one or more principles. Each principle or step of this process might also require specific technical skills in climate data analysis such as coding, statistics, data visualisations, understanding of basics of climate models, etc.

::: {.callout-note title="Note"}
This page does not include principles on how to conduct specific analyses downstream of the climate data, i.e. how to do climate risk assessments or a health impact assessment. It is meant mainly to help users understand how to pick and choose the right data and analysis approaches for analysing the climate hazards of interest.
:::

**How this page is organized:**

- The main text of each principle describes what a user should do at that stage of the process.
- Each principle is followed by an **Important Considerations** callout, which provides background, rationale, and do's and don'ts. This text has more technical depth and may require a basic understanding of some key climate-related concepts.
- Five cross-cutting boxes cover topics that arise across multiple principles. These are separated out for readability and are referenced from the relevant principles.

## Summary of Principles

- **Principle 1: Scope and identify data needs**
  - Identify climate data applications
  - Identify audience for the analysis and results
  - Involve relevant people
  - Determine types of data analyses needed
  - Develop a list of metrics, variables, temporal and spatial scales, scenarios, downscaling, and unknowns
  - Determine risk and uncertainty tolerance
  - Evaluate technical capabilities
  - Evaluate computational capacity
- **Principle 2: Catalog available data**
  - Identify all datasets covering the spatial domain
  - Catalog data details for each dataset
  - Review metadata
  - Identify available user guidance
  - Identify data-related regulations or policies
- **Principle 3: Screen available datasets against requirements**
  - Conduct initial screening for fit of datasets
  - Revisit important data considerations/criteria
  - Assess tradeoffs between datasets
  - If data size is a constraint, revisit spatial and temporal scale choices
  - Select datasets that fulfil the most important data considerations/criteria
  - Consider a preliminary comparative analysis between multiple datasets
- **Principle 4: Assess credibility of data**
  - Identify existing credibility assessments
  - Critically review assessments to understand approach, known biases, and credibility at multiple scales
  - Identify the most pertinent credibility-related considerations and determine if elimination of models/datasets is necessary
  - Document reasons for elimination of models/datasets
  - Cross-check to ensure that data spans a range of outcomes
  - Determine if a context-specific credibility assessment is necessary
- **Principle 5: Sub-select data**
  - Determine whether sub-selection of models is necessary
  - Develop a principled, step-by-step plan for choosing a well-balanced sample
  - Conduct an exploratory analysis to characterize the distribution of model runs
  - Use the distribution plots to choose an appropriate sample based on context
  - Cross-check that the sample spans a range of outcomes
  - Document and communicate the sub-selection approach
- **Principle 6: Analyze data and summarize results**
  - Revisit the purpose and audience for the data analysis
  - Identify metrics, statistical analyses, and aggregations needed to analyze data
  - Develop a step-by-step method to compute metrics, aggregate across scales, and synthesize across models and scenarios
  - Consider model weighting, presenting results as change signals versus absolute values, and framing impact relative to natural variability
  - Evaluate uncertainty
  - Document and communicate the analysis approach and limitations
- **Principle 7: Evaluate and document the analysis**
  - Evaluate if the analysis answered the original questions
  - If questions were not answered, revisit previous principles or reframe the original question
  - Finalize documentation of the workflow
  - Consider a plan and timeline for updating the analysis
  - Determine how the analysis and results should be presented and communicated
  - Archive the most important data and outputs

## Principle 1: Scope and Identify Data Needs

- Identify the various applications that need to use climate data.
- For each application, identify the audience for the specific results that are generated from data analyses.
- Identify the people within your organization who should be involved in climate data needs assessments for each application.
- Determine the type of analyses you would like to conduct with the climate data (e.g. exploratory analyses to examine general trends or patterns, or explanatory analyses where data needs to be used to test a hypothesis or answer specific questions), and what question you would like to answer through the analyses.
- For each application (with the relevant people) develop a list of detailed data needs including at the minimum:
  - Data information including climate variables or metrics (see [Box 1](#box-1))
  - Spatial resolution and extent (see [Box 2](#box-2))
  - Temporal resolution, sampling window, and timeframe (see [Box 2](#box-2))
  - Historical scenarios (see [EPRI's guide to choosing climate projections](https://apps.epri.com/climate-data-user-guide/en/choosing-climate-projections.html))
  - Future scenarios (see [EPRI's guide to choosing climate projections](https://apps.epri.com/climate-data-user-guide/en/choosing-climate-projections.html))
  - Preference for downscaling or bias-adjustment approach, if any (see [EPRI's guide to climate model downscaling](https://apps.epri.com/climate-data-user-guide/en/climate-model-downscaling.html))
  - Any unknowns in the above categories that cannot be determined a-priori
- Determine the risk and uncertainty tolerance for each application (e.g. decisions related to infrastructure resilience could be high-risk with lower uncertainty tolerance, whereas broad regional vulnerability analyses might have lower risk and higher uncertainty tolerance for the climate data).
- Evaluate the technical capabilities of personnel to conduct climate data analyses.
- Evaluate the computational as well as data storage capabilities (or limitations) for data analyses.

### Important Considerations

- Climate data can have a direct influence on broader decision-making within your organization as well as for communities impacted by those decisions. Therefore people from all relevant departments should be included in the data identification process. This may include external experts if subject matter expertise is not available within your organization.
- Different applications may warrant different data choices and may need to be deliberated separately.
- Examine [Box 1](#box-1) and [Box 2](#box-2) for important considerations on how to choose metrics/variables and appropriate spatial and temporal scales for your application.
- In some instances, users may not know a-priori which types of data or approaches are appropriate for specific applications. Therefore some data needs identified at this stage might need to be revisited and iterated on as the analyses are being conducted.
- Risk and uncertainty tolerance can play an important role in the choice of scenarios or models, i.e. choices can depend on whether the risk of overestimating or underestimating extremes is more consequential in a particular application.
- Consider improving your organization's technical capacity to work with climate data through training or hiring.
- Consider improving data storage and computational capabilities if they are restrictive.

::: {#box-1 .alert .alert-primary}
### Box 1: Choosing Variables and/or Metrics 

Users need to make choices about which metrics (and underlying variables) are appropriate for answering questions at different stages of the process, including during:

- Data needs identification (Principle 1)
- Credibility assessment (Principle 4)
- Developing distribution plots for sampling data (Principle 5)
- Data analysis (Principle 6)
- Reporting analyses (Principle 7)

For each stage, select the metric that most closely matches the risks or impacts being studied and is most relevant to the context of the analysis. Ensure that the spatial and temporal scale of a metric matches the impact or risk being studied. Available scientific literature and/or existing planning or policy requirements can help determine which metrics are appropriate for different contexts.

Some questions or applications may require analyzing multiple metrics (e.g. multi-hazard vulnerability assessments, compounding events, heat indices). In such cases, users should check that there is physical consistency among the metrics.

#### Important considerations

- A climate variable is a fundamental atmospheric or oceanic quantity like temperature or precipitation that describes the Earth's climate.
- Metrics can be simple calculations from a single climate variable (e.g. 3-day average temperature), or complex calculations derived from multiple variables (e.g. the Fosberg Fire Weather Index is calculated from temperature, relative humidity, and wind speed).
- Some climate impacts are instantaneous (e.g. high winds) while others are cumulative (e.g. groundwater depletion over many years). Climate metrics should be chosen at the timescale that is most appropriate for the type of impact.
- Choice of metrics may differ at different stages (e.g. credibility assessment metrics may require simpler metrics, while reporting analyses may require sophisticated, derived metrics).
- In some cases, it is hard to a-priori identify the one metric that best represents the specific risk/impact. Consider comparing between different relevant metrics to understand how sensitive your data sample/result is to the choice of metric (e.g. comparing PDSI, SPI, and SPEI for drought analyses).
- Engineering requirements or existing policies may already have well-defined thresholds that can be translated into a metric, such as the temperature rating of equipment, or an unsafe temperature for outdoor work.
- Data availability may strongly dictate your choice of metric.
- Some metrics may be closely related for a given variable (i.e. one metric may be a proxy for another) and users can choose among them based on data availability and other contextual factors (e.g. cloud cover is sometimes used as a proxy for solar irradiance, heat index can be a proxy for wet bulb globe temperature in certain regions).
:::

::: {#box-2 .alert .alert-primary}
### Box 2: Selecting Appropriate Spatial & Temporal Scales

For most analyses, users will need to make choices regarding five spatio-temporal considerations:

- Temporal resolution (daily, hourly, etc.)
- Sampling window (number of years of analyses)
- Timeframe (historical, mid-century, end-of-century, etc.)
- Spatial resolution (the size of grid cell or data at a point location)
- Spatial extent (the area over which data needs to be analyzed)

Key considerations for determining the most appropriate scales are as follows:

**Temporal resolution:** Choice of resolution should be dependent on the specific temporal aspects that are most relevant to the application. These can be identified by qualitatively assessing the temporal nature of the climate hazard of interest and how it interacts with a user's system and planning process (e.g. daily or monthly resolutions may be sufficient for analyzing general trends in temperature or heat, while hourly resolution may be needed for assessing wildfire risk where temporal aspects are much more important).

**Sampling window:** For many applications, users should choose a data window that is able to sufficiently represent the different modes of variability of the climate that are relevant to the region and the application. A 30-year window is broadly recommended to characterize the average conditions and internal variability of the climate. However shorter time windows may be appropriate for some sectoral applications (e.g. those that require a specific focus on current climate).

**Timeframe:** Climate trends are harder to discern in shorter timeframes due to inherent natural variability in the system. Longer-term analyses can provide a better understanding of the direction of change, which can in turn be helpful in interpreting shorter-term trends where some risks may be less visible and harder to discern. Therefore, for applications that require analyses of near-term or short-term time frames, it is recommended that users consider a supplementary assessment of impacts over longer periods of time (e.g. 2070, end of century, etc).

**Spatial resolution:**

- Users must first determine whether they need point location data or can work with gridded data depending on their application. For instance, applications that examine hyper-local issues (e.g. a point-based asset such as a substation) or that involve models parameterized on particular weather stations might necessitate point location data. For analyzing regional climate responses, gridded data might be most appropriate.
- To determine the appropriate resolution of gridded data, users should assess whether the spatial heterogeneity/variability (topographic, climatic, or other) within the region they want to examine is small or large. Finer resolution data could provide greater benefits for regions that are spatially heterogeneous (e.g. areas of complex terrain or regions that transition quickly from water to land) as compared to regions that are more spatially homogeneous (e.g. large plains).

**Spatial extent:** Users should examine an area that is large enough to properly analyze the climate issue or the hazard under consideration (e.g. to analyze the impacts of a heat event on system-level planning, users should examine the entire regional extent where the impacts of the heat events may occur).

#### Important considerations

- Choice of temporal and spatial scales could vary based on multiple considerations including the characteristics of available data, specific temporal or spatial aspects of relevance to the application or planning context, type of variable or hazard, specific regional context, topography, etc.
- When making decisions on appropriate scales, the scale of the decision and the scale that the climate phenomena of interest plays out at are both important to consider.
- Reflect on general assumptions and norms (both within science and decision context) to qualitatively judge the most appropriate scales for the context.
- Other important considerations for temporal scale are as follows:
  - Highest resolution data might not always be the best fit (or necessary) for your application.
  - Finer resolution data is not always better data and in some cases can introduce or amplify biases in the coarser data. For example, studies have shown that increasing the resolution of WRF data for California led to improvements in certain snow and wind metrics, but also led to wet precipitation bias in some regions that was perpetuated and amplified by certain boundary conditions in the coarser data ([Rahimi et al. 2022](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2021JD035699), [Risser et al. 2024](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1029/2023GL105979)).
  - Many studies suggest using a sampling window that is about 30 years. Shorter windows might not adequately represent the various modes of climate variability, and therefore may not be fully representative of the hazards that might impact systems (i.e. there is a possibility of missing out on key hazards). For instance, applications like extreme value analyses require at least 30 years of simulation to appropriately pull event maxima ([Bonnin et al. 2006](https://www.weather.gov/media/owp/hdsc_documents/Atlas14_Volume2.pdf)).
  - Recently, agencies such as NOAA have considered [shorter sampling windows](https://www.ncei.noaa.gov/products/land-based-station/us-climate-normals) (i.e. 15 years), particularly for applications that require more recent climate information, such as predicting [energy system loads](https://kleinmanenergy.upenn.edu/commentary/blog/the-new-climate-normal-for-utility-weather-forecasts/) and informing economic decisions. The appropriateness of using sampling windows that are shorter than 30 years for certain applications (and/or regions) is an active area of [research and deliberation](https://yaleclimateconnections.org/2021/02/updated-yardstick-begs-question-whats-normal-in-a-changing-climate/) ([Livezey et al. 2007](https://journals.ametsoc.org/view/journals/apme/46/11/2007jamc1666.1.xml)).
  - Another instance where shorter time-windows of 5-10 years are commonly used is when users are presenting results as continuous time series rather than comparing climatologies. In such instances, using a rolling average of shorter windows can serve the purpose of smoothing out interannual variability to allow the results to focus on long-term change signals.
  - There may be a need to align timeframe choices with planning cycles and/or with the lifetime of the asset/infrastructure under consideration. However, near-term timeframes have higher noise-to-signal ratios, making it harder to discern trends. Further, climatic changes, as well as the impacts and risks that stem from these changes, could be non-linear and increase at a more rapid rate towards the end of the century. Hence, near-term timeframes might not always provide a holistic picture of long-term risk and impacts, particularly for the higher SSPs. Therefore, a supplemental long-term analysis is recommended even if applications are looking at shorter time-scales.
  - Using [Global Warming Levels](/scientific-guidance/global-warming-levels.qmd) (GWL) as an alternate framework can help overcome some of the challenges relating to timeframes, as this framework is more suited to adaptive planning. However, choosing a single GWL might lead you to miss out on non-linear impacts that are visible at different warming levels, therefore it is recommended that users choose multiple warming levels for their analyses.
- Other important considerations for spatial scale are as follows:
  - Most GCM climate data is gridded, and climate models do not automatically output data at point locations.
  - If point locations are needed, then an appropriate localization approach which includes bias-correction might be necessary.
  - Point location localization requires high-quality historical observations data at that location. If historical data is unavailable, then users would need to assess and rely upon the finest resolution gridded data from the nearest gridcells.
  - Many informed decisions and investments can be made by using lower resolution data that considers more models and plausible future outcomes.
  - When conducting analyses for specific spatial extents that do not match a grid cell, care must be taken to create a rigorous workflow which carefully considers edge cases where, for example, a gridcell may be only partially included in a selected spatial extent. Conducting hyper-local spatial analyses (e.g. using [census tracts](/scientific-guidance/census-tracts.qmd) in urban areas) may require more specialized approaches.
:::

## Principle 2: Catalog Available Data

- Identify all datasets available for your region or spatial domain.
- For each dataset, catalog the relevant details including:
  - Data formats and any transformations/pre-processing that have been conducted
  - Variables or metrics available
  - Spatial and temporal resolution
  - Spatial extent and timeframes of data
  - Future scenarios
  - Historical scenarios
  - Models and corresponding ensemble members
  - Downscaling and bias-adjustment approaches
- Review existing metadata for each dataset including:
  - Approach for dataset development
  - Limitations of the dataset
  - Frequency of dataset updates
  - Accessibility and transparency of methods
- Identify the availability of user guidance for each dataset.
- Identify any relevant regulations, policies, or guidelines related to data use for your region or sectoral application (e.g. guidance on which models, metrics, or scenarios to use).

## Principle 3: Screen Available Datasets Against Requirements

- Conduct an initial screening of all regional datasets (identified in Principle 2) to assess the extent to which they fit/meet your technical data requirements and analysis needs. Note that here you are screening models/data for fit and meeting technical requirements, and not credibility. Credibility-based selection is the next step.
- Revisit all the important data considerations/criteria for your application (identified in Principle 1) such as need for fine resolution data, manageable data size, range of outcomes, statistical power, etc.
- Assess the tradeoffs between different datasets in terms of how well they fit your specific data needs and requirements (e.g. some datasets may offer finer resolution but not a large range of models or scenarios, while others may have more distinct models or more realizations of a single model).
- At this stage, data-size considerations for your applications should be evaluated. For instances where data size is a key limiting factor, you may need to re-visit your choice of spatial and temporal scales with respect to trade-offs on other important criteria (e.g. finer resolution data may preclude the ability to work with a large number of models and scenarios based on data size — see [Box 3](#box-3)).
- Identify all the datasets that fulfill the most important technical considerations/criteria for your application of interest (e.g. if extreme events and daily resolution are most important, then choose datasets that have daily data and a large number of models with many ensemble members that provide statistical power).
- If multiple datasets are deemed a good fit for your application, use a preliminary comparative analysis to evaluate how results may vary, and to see what different types of information each dataset might provide (e.g. one dataset may have more models and scenarios while another could have different types of relevant metrics).

### Important Considerations

- Dataset selection at this stage may be constrained by the availability of specific variables or spatial and temporal scales. Sometimes users may need to re-evaluate or adjust data needs and expectations based on the available data (i.e. if the desired resolutions are not available, users might need to re-evaluate whether coarser data can be used).
- There may be a need to eliminate some datasets that do not have the data you require or do not fit your needs. It is good practice to transparently document and re-evaluate the reasons for selection/elimination of specific datasets.
- Different datasets suit different needs. Take care not to overly rule out datasets at this stage, and keep the eliminations as minimal as possible.
- Different datasets may use different downscaling and bias-adjustment techniques. Evaluate the [advantages and disadvantages](https://apps.epri.com/climate-data-user-guide/en/climate-model-downscaling.html) of each and determine which is most appropriate for your context.
- Once datasets are selected, users may choose to conduct analyses in the cloud to avoid storage and computational constraints. If downloading data is necessary, users should consider the data size and storage constraints before downloading.
- When downloading geospatial data, `.csv` file format may not adequately preserve coordinate and metadata information. Therefore, `.netcdf`, `.zarr`, or other geospatial file formats are preferred.

::: {#box-3 .alert .alert-primary}
### Box 3: Analyzing Data Size Trade-offs

The choices of spatio-temporal resolution, sampling window, timeframe, and spatial extent will have significant implications for data size, potentially leading to subsequent data or computational constraints. So users should first assess whether they are able to choose the "most appropriate" scales for their context (as determined in Principle 1) or if they need to make some trade-offs or compromises due to data size and computational constraints.

Users should then examine the tradeoffs of different choices, i.e. information that is gained or lost by choosing different resolutions, windows, timeframes, or extents, as well as how they interact with the ability to work with multiple models or emission scenarios.

This trade-off analysis can be done either qualitatively (through informed judgements of data size and implications) or by conducting a quantitative preliminary comparative analysis to more directly examine the implications of different choices and their potential trade-offs. For the comparative analysis, start with coarser resolution data or smaller timeframes and then work towards larger or finer sets of data to determine which choices lead to significantly different results and are important to consider.
:::

## Principle 4: Assess Credibility of Data

- Identify existing credibility assessments available in the literature for each dataset. This could be, for instance, a peer-reviewed paper or report defining the applications, intended use, credibility, and limitations of the data.
- Critically review available assessments to determine how well different datasets represent the phenomena, variables, and regions of interest. Include, at a minimum, the following steps:
  - Examining how the assessment was conducted (e.g. spatial and temporal scales, variables, climate processes that were assessed)
  - Determining the appropriateness of the methodology used to generate the datasets for your application (e.g. type of downscaling method used or type of bias-adjustment conducted)
  - Understanding known biases within the dataset that may preclude use for specific regions and/or variables (e.g. near-surface moisture is projected to be higher than historical observations within CMIP6 GCMs)
  - Understanding credibility for the entire dataset, as well as individual models within the dataset, at multiple scales (e.g. global, regional, local) and for different variables of interest (e.g. by examining existing model rankings, if available)
  - Assessing whether the models include a representation of key processes relevant to the application (e.g. lake-ocean effects may be important in some regions and not all models include these processes)
- Based on the review, identify the most pertinent credibility-related considerations for your context (e.g. large biases in relevant variables for some models, need for physical consistency among different variables, appropriate representation of key regional processes), and determine whether it is necessary to remove entire datasets or models from further analyses.
- Transparently document the findings from the review of credibility assessments, and the reasons for inclusion or elimination of specific models/datasets.
- If model eliminations are necessary, cross-check to ensure that the datasets still contain multiple models that span a range of outcomes and robustly characterize uncertainty about future conditions.
- Determine whether a more context-specific credibility assessment of the data is necessary (e.g. if your niche application requires further analysis of credibility for a specific variable or phenomenon). If so, it may require contracting an expert or research agency to conduct such an assessment.

### Important Considerations

- Conducting credibility assessments is a complex scientific endeavor, so users should identify and rely on existing assessments where possible, such as:
  - Peer-reviewed publications and/or guidance materials produced for the datasets (e.g. LOCA2 or [WRF datasets](https://www2.mmm.ucar.edu/wrf/users/wrf_users_guide/build/html/index.html))
  - Broader climate assessments (e.g. state assessments, National Climate Assessment, or IPCC)
  - Credibility assessments for the region(s) of interest (e.g. [Krantz et al. 2021](https://www.energy.ca.gov/sites/default/files/2022-09/20220907_CDAWG_MemoEvaluating_GCMs_EPC-20-006_Nov2021-ADA.pdf), [CA DWR 2015](https://water.ca.gov/-/media/DWR-Website/Web-Pages/Programs/All-Programs/Climate-Change-Program/Climate-Program-Activities/Files/Reports/Perspectives-Guidance-Climate-Change-Analysis.pdf), [Pierce et al. 2016](https://loca.ucsd.edu/~pierce/IEPR_Clim_proj_using_LOCA_and_VIC_2016-06-13b.pdf), [Rupp et al. 2013](https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/jgrd.50843))
- Critically reviewing existing credibility assessments for a user context can also be a complex endeavor, so this needs to be done carefully and intentionally, and in some cases might need consultation with experts.
- While critically reviewing credibility assessments, be aware that:
  - Credibility assessments can be at a dataset-level and/or at a model-level.
  - A good credibility assessment involves examining models at different scales. For instance, evaluating credibility for local applications still requires examining models' ability to represent regional and even global processes.
  - All climate models have some degree of bias relative to the real-world values of climate variables. Models with large apparent biases can still have excellent representation of physical climate processes and produce a credible climate change signal. For this reason, credibility assessments that incorporate evaluation of physical processes are preferred over ones that only focus on variables without evaluating process-credibility.
  - Even if a model is deemed credible for a region, model performance for specific subregions or metrics might vary.
  - A model that represents one metric well may not necessarily represent another metric equally well for the same region. The degree to which model skill is correlated for different metrics is not well understood.
  - High resolution spatial data is not always more credible than coarser spatial resolution.
  - Dynamical and statistical downscaling techniques have unique [strengths and weaknesses](https://apps.epri.com/climate-data-user-guide/en/climate-model-downscaling.html). One is not automatically more credible than the other.
  - Bias-adjusted (also termed bias-corrected) and non-bias-adjusted data are not more or less credible than one another, but each kind may be more appropriate for specific types of use (e.g. if your analysis is focused on a change relative to historical conditions, non-bias-adjusted data can perform just as well as bias-adjusted data).
- Credibility assessments are better suited for eliminating models that do not accurately represent the regional climate (or have large known biases) rather than cherry-picking top performers.
- There may be trade-offs involved while eliminating models based on credibility, therefore users should take care not to overscreen models. Each model makes different (but valid) choices on how various climatic processes are represented and emphasized. The diversity of models reflects the fact that we have incomplete understanding of the future. Therefore it is not recommended to select "one," or even a few, of the best models for a region or an application. Utilizing a set of several credible models can provide users with valuable insights about the range of plausible outcomes.
- If consulting with experts while reviewing credibility assessments, be aware that different scientists may have their own preferences and biases. Seeking a second or third opinion could be valuable. If there are no scientists within your state or region with expertise in credibility assessments, consider experts from other similar regions.
- If multiple datasets are deemed credible, it might be useful to evaluate how results vary across the datasets.
- If a credibility assessment is not available for the dataset relevant to your specific context, include that information as part of your documentation so the level of risk and undefined credibility is transparent to all decision-makers.

## Principle 5: Sub-select Data

- Determine if you are able to utilize all the models and simulations within the credible dataset(s) based on computational capacity, data size limitations, or the type of analysis being conducted. Based on your context, sub-selecting the data may be necessary.
- If you are unable to use the entire dataset, develop a principled, step-by-step plan to identify a well-balanced sample from all available models and simulations within the credible datasets. Note that different sampling strategies may be needed for different applications due to their unique needs (e.g. data sub-selection approaches might differ for applications where users are assessing a worst-case scenario or conducting a stress test analysis versus where users are planning around average changes or quantify uncertainty).
- Conduct an exploratory analysis on the entire dataset to characterize the distribution of models and ensembles across the range of outcomes for the metric(s) of interest as follows:
  - Plot the distribution of the model runs ranging from hottest to coolest, wettest to driest, or based on the magnitude of the change signal or of a relevant metric.
  - If multiple variables are important to your analysis, plot how they change in combination with each other across different model runs (e.g. which models predict hotter and drier conditions vs. hotter and wetter).
  - If there are computational constraints, use a simplified form of the exploratory analysis by choosing a shorter time period, smaller area, or simplified metric. For example, if studying 1-in-x heat events, users may choose to do the model sub-setting using a simpler metric such as annual maximum temperature. This can help avoid the computationally intensive steps that may be involved in using a 1-in-x metric for the analysis, such as fitting a distribution to the data.
- Using the distribution plots from the exploratory analysis, sub-select the most appropriate sample for your context as follows:
  - Sample to (1) match the mean of the full dataset, (2) capture a range or representative variability, or (3) select extreme bounding cases. The option you choose will depend on the focus of your analysis, risk tolerance, and/or additional context around the impacts of the relevant variable (e.g. for worst-case scenario or stress test analyses, users may choose to sample simulations that fall at the extremes or tails; whereas users planning around average changes might pick the mean or choose a sub-set that spans the range of the distribution to quantify uncertainty across simulations).
  - If your application is focused on changes to rare or extreme events, include as many individual simulations as possible to ensure statistical robustness. If available in your dataset, individual models that have large ensembles of simulations should be included, as they provide a useful way to measure changes to extremes.
  - If your analysis is not focused on rare or extreme events, sample a range of models that have diverse physical representations of the climate system, as they can be more valuable than including many simulations from a single model.
- Cross-check that the resultant sample includes an appropriate combination of multiple models, ensemble members, and/or a variety of future scenarios that appropriately captures the goals for the analysis.
- Clearly document the sub-selection approach and communicate it when sharing the results.

### Important Considerations

- For some regions, there may be published analyses or distributions of models that can be leveraged for sampling (e.g. distribution plots characterizing models from hot to cold or wet to dry are often included within credibility assessments like [Krantz et al. 2021](https://www.energy.ca.gov/sites/default/files/2022-09/20220907_CDAWG_MemoEvaluating_GCMs_EPC-20-006_Nov2021-ADA.pdf)).
- Sub-selection always involves tradeoffs, so it is important to do so carefully and transparently. Even with the most careful sampling procedure, there may be a chance of missing plausible worst-case scenarios.
- When sub-selecting, it is essential to avoid unintentionally selecting a biased sample (e.g. unknowingly choosing the hottest three models from a larger set).
- Using the entire sample of all credible models will provide the most comprehensive picture of future projections. But if sub-selecting is necessary, most scientific recommendations suggest that at a minimum the sample should contain 5-10 models, although there may be differences based on specific variables, size of change signal, etc. (see [Pierce et al. 2009](https://www.pnas.org/doi/10.1073/pnas.0900094106), [McSweeney et al. 2014](https://link.springer.com/article/10.1007/s00382-014-2418-8), [Mendlik and Gobiet 2015](https://link.springer.com/article/10.1007/s10584-015-1582-0), and [CA DWR 2015](https://water.ca.gov/-/media/DWR-Website/Web-Pages/Programs/All-Programs/Climate-Change-Program/Climate-Program-Activities/Files/Reports/Perspectives-Guidance-Climate-Change-Analysis.pdf)).
- Sub-selection strategies may differ for applications that require extreme event analysis and internal variability, versus those that do not require analyzing extreme event statistics or internal variability.
  - Applications involving the evaluation of statistics of extreme events or internal variability may require large ensembles to ensure that there are sufficient instances of rare events to adequately examine their properties and frequencies. Therefore these applications may rely on a suite of models with multiple ensemble members.
  - For applications that do not require these analyses, it may not be essential to distinguish among models and ensembles, and each projection can be considered a realization of a plausible outcome.
- For some specific applications like stress tests, it may not be necessary to examine the entire range of plausible outcomes, and users might specifically choose the models or simulations that fall in the tails of the distribution.

## Principle 6: Analyze Data and Summarize Results

- Revisit the specific purpose and audience for which you are analyzing the data (identified in Principle 1) and identify the types of questions you intend to answer with the data.
- Based on the above determined purpose, identify the metrics (see [Box 1](#box-1)), the types of statistical analyses, and spatial and temporal aggregations (see [Box 4](#box-4)), etc. needed to analyze, visualize, and/or interpret the data. Note that these may be the same as those identified in Principle 1 or could be more detailed or nuanced than the initially identified needs.
- Develop a step-by-step method on how to conduct the analysis and summarize results. This may include computing metrics, aggregating across spatial and temporal scales, and synthesizing data across models and emission scenarios/warming levels. Note that the order in which you perform each step will have a significant impact on the final results.
- Ensure that your analysis considers the following:
  - Whether projections need to be weighted differently based on the number of ensemble members per model, model independence, model credibility, etc.
  - Whether change signals or absolute results are more appropriate for your analysis context. If calculating change signals, determine the most meaningful baseline or reference period (see [Box 5](#box-5)). If using absolutes (such as measuring exceedances of a threshold), ensure that bias-adjusted data is used. For a change signal, both bias-adjusted and non-bias-adjusted data can still produce valid delta signals.
  - Evaluate and frame the significance of climate impacts relative to the range of natural variability that exists within the climate system.
- Evaluate uncertainty in your analysis as follows:
  - Review and understand the different types of uncertainties in climate data (e.g. internal variability, model uncertainty, scenario uncertainty) and where they may arise within your analysis (see [EPRI 2024](https://apps.epri.com/climate-readi-hazard-guide/en/8-Uncertainty.html) and [Jagannathan et al. 2024](/scientific-guidance/general-climate-guidance/using-climate-projections.qmd)).
  - Heuristically identify the types of uncertainties that are most important to assess for your context. Although all sources of uncertainty are important to consider, the relative importance of each depends on a given application, risk tolerance, etc.
    - Consider the timeframe of your analysis to determine whether specific types of uncertainty may be more relevant than others. For many regional applications, internal variability dominates for the near-term. Model and scenario uncertainty increase in their relative importance over time, while the importance of internal variability tapers over time. Scenario uncertainty only starts to matter after mid-century ([Hawkins and Sutton 2009](https://journals.ametsoc.org/view/journals/bams/90/8/2009bams2607_1.xml)).
    - Additionally, consider if your choice of metrics/variables, temporal and spatial scales, and temporal and spatial aggregations impact the relative importance of the different types of uncertainty.
  - Choose the appropriate method for evaluating uncertainty based on the type of uncertainty/ies identified as most relevant.
    - Scenario uncertainty can be evaluated by considering multiple SSPs or GWLs.
    - Model uncertainties can be examined by interpreting a range of possible outcomes across multiple models.
    - Internal variability can be analyzed by using large ensembles of a single model.
  - Overall, examine a range of plausible future outcomes using different datasets, models, emission scenarios, and downscaling approaches to build contextual awareness of an uncertain future. Specific recommendations related to these considerations are also included within each of the previous principles, such as when assessing data credibility, sampling, etc.
- Transparently document and communicate the analysis approach (including uncertainty evaluations) as well as any limitations of the analysis or aggregations.

### Important Considerations

- Determination of the metrics, types of analyses, aggregations, etc. should be done carefully and intentionally, based on the most valuable information that needs to be conveyed.
- Very different interpretations of the data can arise through different approaches to aggregating, summarizing, or visualizing across the dimensions of space, time, simulation, model, and scenario.
- The most appropriate way to present results depends on the context and audience. For any given analysis, different audiences may require different types of metrics or statistical approaches. For example, some users may require a specific result/explanatory analysis (e.g. a 1-in-x event to plug into a downstream model), while others may need a simple exploratory analysis of trends.
- Because every model has unique biases and systematic errors, absolute numbers (e.g. temperature of the hottest day of the year) from different models can only be directly compared if they have all had a similar bias-adjustment applied to align with a trusted observational data source. If a mixture of bias-adjusted and non-bias-adjusted models are used, comparisons should only be made between change signals (e.g. future change in degrees of the hottest day of the year).
- Users should qualitatively consider how known biases in data might impact results in their direction and extent. For example, studies show that CMIP6 GCMs may be over-estimating water vapor in the US Southwest ([Simpson et al. 2023](https://doi.org/10.1073/pnas.2302480120)). Therefore heat impact studies using metrics that include relative humidity variables (such as heat index) may overstate the impacts due to the inherent biases in the models. Such potential biases should be transparently documented in user analyses.
- Future climate data will always have inherent uncertainty because there is no way to verify and validate events that have not happened yet.
- Uncertainties do not invalidate the usefulness of climate data for adaptation; rather they represent the complexity and range of potential future outcomes.
- Some relevant scientific concepts, such as whether downscaling increases or decreases uncertainty, and how the relative significance of different sources of uncertainty varies for different spatial and temporal scales, are still emerging areas of research.

::: {#box-4 .alert .alert-primary}
### Box 4: Aggregation Across Spatial and Temporal Scales

When conducting spatial (aggregating across gridcells) or temporal (aggregating across months/years) aggregations, first examine climate impacts without aggregation to understand the spatial and temporal variability and distribution of the data. This is because important climate change signals and information about uncertainty can be lost when aggregating across different locations, time scales, or models. Therefore it is recommended to first examine climate impacts without aggregation, and then aggregate data at the end, once the variability and distribution have been thoroughly examined.

Consider reporting the most appropriate statistics for the region rather than defaulting to spatial or temporal averaging. These could include distributional statistics over the aggregated area, spatial variability within a county, temporal variability over a season, etc.

Consider the homogeneity of the climate hazard as it overlaps with the homogeneity of the spatial area or timeframe being aggregated over (e.g. aggregating heat over homogeneous plains versus precipitation over heterogeneous topography can have very different implications for the eventual results).

Exercise caution when aggregating over grid cells for assessments of extremes, such as in [extreme value analysis](/scientific-guidance/extreme-value-analysis.qmd), where there is potential for biasing results toward the most extreme value in the area and/or missing an extreme of interest.

If your application involves presenting data as a time series, the sampling window for aggregation should be long enough to smooth out large variations from diurnal or seasonal cycles if they are not the focus of the analysis. If your application needs to preserve interannual or multi-year variability, ensure that the window for aggregation is short enough to evaluate the change signal relative to the magnitude of natural variability.

When presenting aggregated results, transparently document the types of impacts that might be missed due to aggregation across different locations, grid cells, or years (e.g. averaging over large spatial areas could lead to missing out on specific distributional impacts for different communities, which might have equity implications). Consider reporting other distributional statistics in addition to documenting the limitations in the results.
:::

::: {#box-5 .alert .alert-primary}
### Box 5: Computing Change Signals

The appropriate reference period for computing change signals depends on the goals of your analysis. Choosing different reference periods can drastically influence the calculated change signal, not just in magnitude but also in spatial patterns and event frequencies. Some common choices include:

- **Pre-industrial period** (e.g. 1850-1900) – Captures the full, cumulative impacts of greenhouse gas-driven climate change. This is consistent with international targets for limiting global climate change (to 1.5°C of global warming), and is the earliest reference period usable with most global climate models.
- **Recent historical baseline** (e.g. 1980-2010) – Focuses on changes relative to recent times when we have fairly complete observational records and "modern" infrastructure, societal function, etc. This is more common for climate impact studies and adaptation planning.
- **Present conditions** (e.g. 2015-2040) – A more difficult-to-define reference period, due to the need for assumptions about how current trends will continue, but potentially useful for very specific operational planning.

It is generally recommended that the chosen baseline be at least 30 years long to capture the range of year-to-year fluctuations in climate. However shorter time windows may be considered for some sectoral applications (e.g. those that require a specific focus on current climate).
:::

## Principle 7: Evaluate and Document the Analysis

- Critically evaluate whether your findings answered the original question(s). Check back in with the people who were involved in determining data needs for the application.
- If you determine that the results were not sufficient to answer your original question(s), either reframe the analysis by re-visiting one or more of the above principles, or reframe the original question so that the available data can sufficiently answer it.
- Finalize the documentation for your analysis once you determine that the results are sufficient. At a minimum, this should include the steps taken within your workflow, as well as limitations, assumptions, and decisions made at each step.
- Consider a plan and timeline for updating, improving, or changing the analysis as new information or resources become available.
- Determine the format in which the analysis and results should be presented and communicated with the intended audience(s) (e.g. reports, one-pagers, figures/maps, presentation formats).
- Consider archiving the data needed to reproduce your final analysis. If space constraints prevent downloading or retaining the full dataset, consider saving a smaller derived or processed dataset to enable future changes to final calculations.

### Important Considerations

- Climate data analysis can be an iterative process. It often takes multiple evaluations and iterative data assessments to develop a robust analysis that produces results that sufficiently answer a question.
- Sometimes the questions we ask of the data cannot be answered, because of the data's inherent limitations. It is important to understand that a "non-result" can still be a valid answer to your original question and may provide meaningful information about the question and/or analysis (e.g. the uncertainty range is too large to distinguish a signal, or the statistical significance is too low). Do not cherry-pick results to answer the original question.
- The goal of documenting your workflow should be to ensure that others can replicate or build upon your analysis in the future. Consider focusing on: transformations to the original dataset, spatial or temporal aggregations or disaggregations, coordinate system transformations, metric calculations, statistical tests applied, technical documentation of developed code, and data download format.
- Consider sharing your results, data, and analysis via an open-source forum, such as an open-access code repository (e.g. GitHub), online blog post, or open-access journal (if appropriate). Be aware that many scientific journals and regulatory institutions strongly recommend — if not require — that code and data be open-access and citable via DOI.

## Acknowledgments

Kripa Jagannathan and Nancy Freitas contributed equally to this document. Naomi Goldenson and Grace Di Cecco provided review and feedback. This work was supported by California Energy Commission (CEC) funding.
