---
title: "Overview"
author: "Cal-Adapt Analytics Engine Team"
date: "2024"
date-modified: "2026-05-21"
format:
  html: default
  pdf: default
---

## About this material

These pages on using climate projections for decision making offer Analytics Engine data users a set of guiding materials on the most appropriate ways to use climate data for decision making. It includes an explanation of why such guidance is important, provides answers to specific data-related questions that users commonly have, and includes a set of guiding principles (or recommended practices) for climate data use. These guidelines can be utilized by any technical or semi-technical data user to better understand the Do’s and Don’t of working with climate data in the Analytics Engine. By understanding how to effectively integrate climate data into sectors such as energy, municipal planning, natural resource management, and public health, data users can better anticipate and mitigate the impacts of climate change.

## How can climate data inform decision-making?
Characterizing changing climate conditions is vital for planning and adaptation. Many sectors and communities are grappling with a growing need to use climate data to anticipate and plan for near- and long-term changes. By assessing the range of possible future conditions under a changing climate, communities can proactively plan for actions that can reduce the impacts of climate change and safeguard lives, livelihoods, and landscapes for decades to come.

The historical and future climate data available on the Analytics Engine can be used to analyze a variety of questions related to climate risks for an agency, community, or region. For such analyses, climate data is often used in combination with other qualitative and quantitative data, such as socioeconomic data, information on institutional capacities, local knowledge, etc. For instance, investor-owned electricity and natural gas utilities in California are required to undertake Climate Adaptation and Vulnerability Assessments. These assessments rely on climate as well as other types of data to identify the populations, infrastructure, and natural systems that are at risk of climate impacts, and to evaluate the utilities’ ability to adapt to such risks.

For an introductory primer on using climate information in risk and impact assessments, users can refer to this [Guidance published by the White House](https://bidenwhitehouse.archives.gov/wp-content/uploads/2023/03/Guide-on-Selecting-Climate-Information-to-Use-in-Climate-Risk-and-Impact-Assessments.pdf). Users can also peruse this comprehensive [Climate Data Users Guide](https://apps.epri.com/climate-data-user-guide/en/) developed by the [Electric Power Research Institute](https://www.epri.com/) (EPRI) which provides a fundamental understanding of the various aspects of using climate data. EPRI’s guide includes details about key concepts such as climate models, downscaling, choosing projections, and sources of historical and future climate data. Other valuable sources are also listed in the Analytics Engine website’s [References](/general-resources/external-references.qmd) page. Definitions of key terms are available on the [Glossary](/glossary/index.qmd) page.

## How should guidance on climate data be used?
Using projections of future climate to inform decision making is an inherently complex process. The science on climate change is continuously being improved and updated, and new datasets and tools for analyzing climate data are actively being developed. Policy and regulation are also evolving to better integrate future climate information, but are faced with difficult questions about how to do this in effective and rigorous ways. Developing a suitable approach for using climate projections depends on several factors, including: the climate-related question that a user wants to answer, the decision that is being made with the climate data, the type of data that is available for the region and decision-context, regulations or mandates for data use, users’ technical capacities to work with climate data, users’ limitations for handling large datasets, users’ risk tolerance, planning timeframes, compatibility of the climate data with other data or frameworks that the user is working with, etc.

Due to this highly contextual nature of climate data use, there can be no one-size-fits-all guidance for how climate models and data should be used to answer specific planning or management-related questions. To this end, the Analytics Engine has undertaken a co-produced and deliberative process that is rooted in practice, regulation, and science, to develop a more flexible set of guiding materials. The following sections will offer context-specific answers for how to use the data available in the Analytics Engine (Guidelines section) as well as general scientific principles on appropriate uses of climate projections (Guiding Principles section [Upcoming]). However, the onus will ultimately always be on the user to identify the best approach for data use within their specific context. It is critical that climate data users incorporate guidance that is based in scientific best practices, such as what is outlined below, to ensure the integrity and appropriate interpretation of their analyses. As climate data and related policies are updated, guidance on data use will also necessarily evolve. Therefore users’ approaches to climate data should be flexible and adaptable to improvements over time. For further specific questions, please reach out to analytics@cal-adapt.org.

## Limitations of these guidelines 
- These guidelines provide users with a scientifically-grounded starting point for how to use climate data to answer real world questions. However, the onus is ultimately on the user to identify whether, and to what extent, these broad guidelines are sufficient for their specific context. There may be complex or nuanced cases where these guidelines either do not apply or are insufficient.
- These guidelines are only applicable to the climate projections data that are hosted in the AE. While some of the key takeaways could also be more broadly relevant, their applicability to other regions or planning contexts has not been examined.
- Some of the recommendations in the guidelines require access to computing resources, tools, and notebooks, such as those in the AE.
- These guidelines were developed based on the perspectives of a diverse but limited set of experts and their understanding of the usability of LOCA2-Hybrid and WRF datasets. As the credibility and actionability of this data is further examined by other scientists and practitioners, some of the guidelines might need to be re-considered.
- These guidelines have not yet been empirically tested/examined in terms of where (and for which applications) they work and where they do not. As users work through these guidelines, if there are suggestions for improvements please reach out to analytics@cal-adapt.org.
- These guidelines are not static. They are meant to be updated continuously over time as practical, scientific, and regulatory understanding of climate change evolves and as new data emerges.

## Guideline development process 
These guidelines have been developed as part of the CEC-funded project EPC-20-007 with support from Amazon Sustainability, titled [“A Co-Produced Climate Data and Analytics Platform to Support California's Electricity Resilience Investments”](https://www.energizeinnovation.fund/projects/co-produced-climate-data-and-analytics-platform-support-californias-electricity-resilience). The main aim of this project is to provide customized data, advanced analytics, and powerful cloud computing resources to support climate-informed planning and research to improve resilience in the electricity sector. The project uses a “co-production” approach, where the data, tools, analytics, and guidance documents (including these guidelines) are collaboratively developed alongside key energy sector climate data users and a diverse group of scientists.

The initial set of questions that have been answered in this section were developed based on interviews and focus groups with energy sector climate data users. In these interviews, users identified the most common challenges that they encounter while using climate data for planning and adaptation purposes. The initial answers to these questions were drafted by three climate scientists and two social scientists who are part of the Analytics Engine project team. These preliminary answers were informed by the latest climate science literature as well as first-hand knowledge of the issues faced by climate data users. The answers were then edited and refined through a rigorous and iterative process that spanned several months, and incorporated the perspectives of a wide-range of data users (such as energy utilities, state agencies, energy consultants), scientists (including climate scientists, climate data producers, social scientists, energy sector specialists), as well as software tool developers. This process included gathering both written and verbal feedback through deliberative focus group discussions. In particular, the project team from CEC’s EPC-20-006 project “Development of Climate Projections for California and Identification of Priority Projections” provided extensive feedback on several versions of the document.

## Acknowledgements and Citation
Guidance materials in this section were developed through many, often painstaking, deliberations and discussions with many people within and outside the Analytics Engine project team. Within the Analytics Engine team, Nancy Freitas led and managed the conceptualization and operationalization of all of the guidance-related materials that appear on the Analytics Engine website, with support from Kripa Jagannathan, Justine Bui, and Mark Koenig. Victoria Ford helped to develop the case examples and analytics that are referred to in this document. Justine Bui supported the refinement of the content. Eric Lehmer supported the development of the web-based version of the document. The rest of the Cal-Adapt: Analytics Engine team provided valuable feedback on various versions of this document, and were integral thought leaders for the design of all of the AE’s guidance materials.

Outside of the core Analytics Engine team, the project team members of the EPC-20-006 project "Development of Climate Projections for California and Identification of Priority Projections" helped to edit and refine this document. Specifically, Dan Cayan (Scripps, UC San Diego), David Pierce (Scripps, UC San Diego), Stefan Rahimi (UCLA and University of Wyoming), Julie Kalansky (Scripps, UC San Diego), and Alex Hall (UCLA) provided extensive feedback on several sections of the document. Alexander Pusch (SCE), Alexandria Chwierut (SCE), Eric Kuhle (PG&E), Michael Mak (Pathways Climate), Lindsay Luchinsky (Pathways Climate), as well as other members of the Cal-Adapt: Analytics Engine user engagement team provided critical feedback on the first version of this document. Alan Rhoades (LBNL) also supported the development of a few draft answers.

Finally, Kripa Jagannathan led the content development for the Guidelines Q&A, with support from Nancy Freitas. Owen Doherty, Andrew Jones and Naomi Goldenson provided technical expertise in drafting the answers.