---
title: "Our Co-Production Process"
citation: false
format:
  html: default
---

## What Is Co-Production?
One of the Analytics Engine's unique aspects is the use of a "co-production" process to build and grow the platform. In co-production, data and tool developers, users, scientists, decision-makers, and other key energy sector experts work collaboratively and iteratively to develop Analytics Engine tools, functionalities, and guidance. This approach draws from best practices and lessons learned in academic literature and practical case studies on developing actionable climate data and services.

## How Our Co-Production Process Began
The Analytics Engine's intensive co-production engagements began in 2021 through interviews with key energy sector climate data users, to understand how they used climate data, the challenges they faced, and how to design the Analytics Engine to best support their needs. This was followed by a workshop (September 28-30, 2021) that included a broader set of California climate data users and decision-makers. During the workshop, participants collaboratively finalized a set of use cases for the Analytics Engine. These use cases continue to anchor the data, analytics, and guidance being developed within the project. Based on interest from workshop participants, a core "working group" was also identified to continue engaging with the [project team](our-team.qmd) in an iterative manner. The working group comprises energy sector data users representing utilities, state agencies, and energy consulting firms.

## Ongoing Engagement
Since 2021, the Analytics Engine team has held regular working group meetings to continue user engagement, present work-in-progress, and seek feedback to improve the usability of the Analytics Engine's products. These meetings also provide an avenue for the project team and users to jointly discuss overall project priorities and propose alternatives where desired. In addition to the working group meetings, select energy sector users are engaged on a 1:1 basis. This focused engagement enables technical deliberations on specific topics and usability testing of newly developed data and tools. The team also offers occasional webinars and written update reports to reach broader audiences. Overall, the goal of this co-production approach is to ensure that the Analytics Engine not only helps energy sector data users analyze climate data effectively (through data and analytics), but also guides them on the most appropriate ways to use climate data for planning and decisions (through guidance and other learning-oriented products).

## Get Involved
Energy sector climate data users in California interested in joining structured working group discussions are encouraged to contact analytics@cal-adapt.org to learn more about the mutual responsibilities, expectations, and timelines for participation.

## Related Resources

Freitas, N. L., Jagannathan, K., Bui, J., Ford, V. L., Krantz, W., Buddhavarapu, S., Chen, C., Conrad-Saydah, A., Koenig, M., Doherty, O., & Jones, A. D. (2026). Co-Producing Climate Services for California's Energy Sector. *Earth's Future*, 14(7), e2025EF005959. <https://doi.org/10.1029/2025EF005959>

Jagannathan, K., Jones, A. D., & Ray, I. (2021). The Making of a Metric: Co-Producing Decision-Relevant Climate Science. *Bulletin of the American Meteorological Society*, 102(8), E1579–E1590. <https://doi.org/10.1175/BAMS-D-19-0296.1>

Kolstad, E. W., Sofienlund, O. N., Kvamsås, H., Stiller-Reeve, M. A., Neby, S., Paasche, Ø., Pontoppidan, M., Sobolowski, S. P., Haarstad, H., Oseland, S. E., Omdahl, L., & Waage, S. (2019). Trials, Errors, and Improvements in Coproduction of Climate Services. *Bulletin of the American Meteorological Society*, 100(8), 1419–1428. <https://doi.org/10.1175/BAMS-D-18-0201.1>
